### PR TITLE
Add static flag

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
Abandoning in a week.

**Comment by dcoutts** [comment]
This looks useful, though I don't understand the choice of name for the flag. What this really controls is if we used the bundled sources vs the system library.

**Comment by dcoutts** [comment]
Rebased, renamed the flag and merged in https://github.com/haskell/zlib/commit/c6803c78c6dbef431cfa169dd1ace739a573ed5a

**Comment by hasufell** [comment]
Thanks! Missed this. :clinking_glasses:

**Pull request closed without merging**
