### PR TITLE
Relax base bounds for ghc-9.0.1

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
Tests pass with ghc-9.0.1.

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/4955.

**Comment by emilypi** [comment]
@asr when CI is green, I'll merge this for you so we can get Agda unblocked. Thanks

**Comment by emilypi** [comment]
@facundominguez i've fixed the conflicts in the latest commit to keep things moving. It looks like this PR requires a release of `async` and potentially a few other packages with GHC 9.0 support before we can merge this. This will be a few weeks or more to coordinate everything, but it's on my radar and we'll get it moving when we can.

**Comment by Bodigrim** [comment]
>  It looks like this PR requires a release of `async` and potentially a few other packages with GHC 9.0 support before we can merge this. 

@facundominguez could you please relax bounds to allow `tasty-1.4`? It does not depend on `async`, and everything compiles just fine with GHC 9.0, so we do not need to wait for anyone else.

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
@emilypi I think this is ready to go.

**Comment by Bodigrim** [comment]
@emilypi ping

**Comment by emilypi** [comment]
@Bodigrim yep, i hear you. I still don't have Hackage perms cc @dcoutts

**Review by emilypi — APPROVED** [review]

**Pull request merged**
